language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-radian' ]; then cd .. && eval "mv $currentfolder generator-radian" && cd generator-radian; fi

